version: '3.8'

services:
  app:
    build: .
    container_name: user_directory_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_directory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: your_jwt_secret_key_min_32_chars_long_for_development
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  test:
    build:
      context: .
      target: build
    command: mvn test

  postgres:
    image: postgres:15-alpine
    container_name: user_directory_db
    environment:
      POSTGRES_DB: user_directory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 