spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_directory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    jwt:
      secret: ${JWT_SECRET:your_default_jwt_secret_key_min_32_chars_long}
      expiration: 86400000 # 24 hours in milliseconds

server:
  port: 8080

logging:
  level:
    org.springframework.security: DEBUG
    com.example.userdirectory: DEBUG 